### ISSUE TITLE
ImgOpener openImage support for directly reading IRandomAccess

### ISSUE THREAD

**Issue by kmader** [imglib/imglib2#81] opened 2014-12-15 14:30 UTC
Currently the ImgOpener tool only allows data to be opened from a String or IFormatReader. While it is possible to implement entirely new LocationServices to read files from another file-system, it would be easier for some projects to enable creating a reader directly from a IRandomAccess or InputStream and a string indicating the filename (for selecting types). Particularly when creating a library which uses ImgLib2 to read and process images, it is quite heavy to write a new custom LocationServices when reading is the only needed ability.

**Comment by ctrueden** [comment] 2015-05-12 21:28
I am closing this, since it is really a duplicate of scifio/scifio#237.

There is now an initial PR for the underlying framework which will make it all possible: scijava/scijava-common#166. We are getting closer! :yum:

**Closed by ctrueden** 2015-05-12 21:28 UTC
